apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:
    config:
      security:
        apiSecurity:
          overrideBaseUrl: https://ac1ba43abb49a49e6b4f254000092352-780995260.us-east-2.elb.amazonaws.com/api  # Public API (Gate) url. Using the same hostname for deck and gate only works when exposing spinnaker with ingress.
          corsAccessPattern: https://ac1ba43abb49a49e6b4f254000092352-780995260.us-east-2.elb.amazonaws.com
        uiSecurity:
          overrideBaseUrl: https://ac1ba43abb49a49e6b4f254000092352-780995260.us-east-2.elb.amazonaws.com       # Public UI (Deck) url.
    profiles:
      gate:
        server:
          servlet:
            context-path: /api
    service-settings:
      gate:
        healthEndpoint: /api/health
